name: Deploy to AWS S3

on:
  workflow_dispatch: # Trigger thủ công
  workflow_run: # Trigger tự động sau khi build thành công
    workflows: ["Build and Upload Artifact"]
    types:
      - completed
    branches: [main, dev]

permissions:
  contents: read
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Chỉ chạy khi workflow build thành công và branch là main hoặc dev
    if: ${{ (github.event.workflow_run.conclusion == 'success' && contains(fromJSON('["main", "dev"]'), github.event.workflow_run.head_branch)) || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Debug workflow run info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow run head branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Repository: ${{ github.repository }}"

      - name: Download vite-dist.zip from S3
        run: |
          aws s3 cp s3://${{ secrets.ARTIFACT_BUCKET }}/vite-dist.zip vite-dist.zip
          unzip vite-dist.zip -d dist
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3 Website Bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: dist
